version: '3.8'

services:
  ftp:
    image: stilliard/pure-ftpd:hardened
    restart: unless-stopped
    ports:
      - "21:21"

  http:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"

  imap:
    image: instrumentisto/dovecot
    restart: unless-stopped
    ports:
      - "143:143"
      - "993:993"

  mysql:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  ssh:
    image: rastasheep/ubuntu-sshd
    restart: unless-stopped
    ports:
      - "22:22"

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  smb:
    image: dperson/samba
    restart: unless-stopped
    command: '-u "user;password" -s "public;/share;yes;no;no;user"'
    ports:
      - "445:445"
      - "139:139"

  nfs:
    image: erichough/nfs-server
    restart: unless-stopped
    volumes:
      - ./exports:/exports
    ports:
      - "2049:2049"

  rabbitmq:
    image: rabbitmq:latest
    restart: unless-stopped
    ports:
      - "5672:5672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    restart: unless-stopped
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
